# Generated by Django 5.2.16 on 2026-07-21 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('Kerajinan Kayu', 'Kerajinan Kayu'), ('Meubler', 'Meubler'), ('Alat Serbaguna', 'Alat Serbaguna')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('harga', models.PositiveIntegerField()),
                ('kondisi', models.CharField(choices=[('Baru', 'Baru (Brand New)'), ('Mulus', 'Mulus'), ('Bagus', 'Bagus')], max_length=20)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif / Dijual'), ('Terjual', 'Terjual')], default='Aktif', max_length=20)),
                ('lokasi', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
