# Generated by Django 5.2.16 on 2026-07-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_wa',
            field=models.CharField(default=62085743151887, help_text='Contoh: 6281234567890 (kode negara, tanpa + atau 0 di depan)', max_length=20),
            preserve_default=False,
        ),
    ]
