# Generated by Django 5.2.16 on 2026-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_no_wa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kondisi',
            field=models.CharField(choices=[('Ready', 'Ready Stock'), ('PreOrder', 'Pre Order')], max_length=20),
        ),
    ]
