# Generated by Django 5.2.16 on 2026-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_kondisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sembunyikan_harga',
            field=models.BooleanField(default=False, help_text='Centang untuk menyensor harga di halaman publik, misal Rp 10000 tampil jadi Rp 1xxxx'),
        ),
    ]
