# Generated by Django 5.2.16 on 2026-07-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sembunyikan_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spesifikasi',
            field=models.TextField(blank=True, help_text='Detail ukuran, bahan, berat, cara pakai, dll.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto utama/sampul produk', null=True, upload_to='produk/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='produk/tambahan/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
