# Generated by Django 5.2.16 on 2026-07-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_spesifikasi_alter_product_foto_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('Kerajinan Kayu', 'Kerajinan Kayu'), ('Kerajinan Umum', 'Kerajinan Umum'), ('Mebel', 'Mebel'), ('Alat Serbaguna', 'Alat Serbaguna'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
    ]
