# Generated by Django 5.2.16 on 2026-07-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jumlah_terjual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('Kerajinan Kayu', 'Kerajinan Kayu'), ('Mebel', 'Mebel'), ('Alat Serbaguna', 'Alat Serbaguna'), ('Kerajinan Umum', 'Kerajinan Umum'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
    ]
