# Generated by Django 5.2.16 on 2026-07-22 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_jumlah_terjual_alter_product_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_saat_itu', models.PositiveIntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='products.product')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
