# Generated by Django 5.2.16 on 2026-07-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_salerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah stok tersedia (khusus untuk kondisi Ready Stock)'),
        ),
    ]
