# Generated by Django 5.2.16 on 2026-07-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('Kerajinan', 'Kerajinan'), ('Furniture', 'Furniture'), ('Alat Serbaguna', 'Alat Serbaguna'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
    ]
