# Generated by Django 5.2.16 on 2026-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_hpp',
            field=models.FileField(blank=True, help_text='File Excel HPP (Harga Pokok Produksi) — hanya terlihat oleh Anda sendiri, tidak ditampilkan ke pengunjung.', null=True, upload_to='hpp/'),
        ),
    ]
